name: meditation_creation_app
description: "A premium meditation app that allows users to create fully customizable meditations."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  provider: ^6.0.5
  riverpod: ^2.4.1
  flutter_riverpod: ^2.4.1
  
  # Navigation
  go_router: ^10.1.2
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.1
  
  # Firebase - using versions that work well on web
  firebase_core: ^2.14.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  firebase_analytics: ^10.4.4
  
  # Audio
  just_audio: ^0.9.34
  audio_service: ^0.18.10
  flutter_sound: ^9.2.13
  audio_session: ^0.1.16
  
  # HTTP Client
  dio: ^5.3.2
  
  # UI Components
  flutter_animate: ^4.2.0
  smooth_page_indicator: ^1.1.0
  lottie: ^2.6.0
  fl_chart: ^0.63.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  flutter_markdown: ^0.6.17
  
  # Utils
  intl: ^0.18.1
  path_provider: ^2.1.1
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  url_launcher: ^6.1.14
  permission_handler: ^10.4.5
  connectivity_plus: ^4.0.2
  uuid: ^3.0.7
  
  # In-App Purchases
  in_app_purchase: ^3.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/audio/voices/
    - assets/audio/music/
    - assets/audio/nature/
    - assets/audio/ambient/
  
  # Temporarily commented out fonts until we have the actual files
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Montserrat-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #         weight: 700
  #   - family: Lora
  #     fonts:
  #       - asset: assets/fonts/Lora-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Lora-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/Lora-Bold.ttf
  #         weight: 700
